### PR TITLE
Corrections

### PR DESCRIPTION
**Pull request by kekuBT**
changed a color from --neutral-color-white to rgba(255, 255, 255, 0.7)
changed a:hover from --accent-color-cyan to --neutral-color-white
added text decoration - underlined to a:hover
changed .nav-bar ul li margin-left from 1rem to 2.75rem
added margin top -  negative 10% to  .intro img .productive img
added color: rgba(255, 255, 255, 0.8) to p
changed button:hover from var(--accent-color-blue), var(--accent-color-cyan)) to hsl(176, 55%, 70%)
changed button height from 3rem to 3.3rem
added  text decoration - none to .content-link:hover
added margin-top -  5% to .bg-quotes
added margin-top - negative 6% to .testimonial-item
changed .testimonial-item to  padding - 30px 20px 10px 30px
changed .testimonial-item-reviewer img width and height from 50px to 30px
added .testimonial-item-reviewer-text h4 and .testimonial-item-reviewer-text p
and some adjustment in the footer

### CODE REVIEW

**Comment by kekuBT** [comment]
You can merge it now.

**Comment by enweazudaniel** [comment]
@kekuBT 👌

**Comment by kekuBT** [comment]
here look at it then tell me if there is a mistake I didn't notice

**Comment by kekuBT** [comment]
last commit.

**Comment by enweazudaniel** [comment]
@kekuBT good work!

**Pull request merged**
